<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Online Statements</name>
   <tag></tag>
   <elementGuidId>88a97e92-dbf0-49e7-b2bf-efe1acb01780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='online_statements_tab']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#online_statements_tab > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd8d4f96-e823-4322-99c0-f00a1b1ea901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/bank/redirect.html?url=online-statements.html</value>
      <webElementGuid>ac247505-73c0-4407-aed0-74dc62c10748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Online Statements</value>
      <webElementGuid>d12b510c-a576-4cd7-9931-7f20eb6520ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;online_statements_tab&quot;)/a[1]</value>
      <webElementGuid>e247588c-0299-48d0-b8b7-f6332c43de5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='online_statements_tab']/a</value>
      <webElementGuid>935f37d0-e445-4907-aff7-2d561b643d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Online Statements')]</value>
      <webElementGuid>f4bee2c9-a071-4202-a8aa-39e14636e21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Money Map'])[1]/following::a[1]</value>
      <webElementGuid>19f379df-d3d3-47a1-92ab-87d2944052e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay Bills'])[1]/following::a[2]</value>
      <webElementGuid>3796d692-8d9b-4531-85cb-86aaa2dc8152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inflow'])[1]/preceding::a[1]</value>
      <webElementGuid>163d41eb-7f53-48a1-801b-55502aad4b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/preceding::a[1]</value>
      <webElementGuid>83e20d45-cbfe-4b10-81e8-b6dbf0ccb8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Online Statements']/parent::*</value>
      <webElementGuid>db8376c6-c9ed-4ea3-863f-bbaccd9285c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/bank/redirect.html?url=online-statements.html')]</value>
      <webElementGuid>8954f1f8-fcf9-4363-92db-e4398630d9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>e11d7564-b91f-4edf-88e3-23709caefc61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/bank/redirect.html?url=online-statements.html' and (text() = 'Online Statements' or . = 'Online Statements')]</value>
      <webElementGuid>e113a0cd-c968-4377-8e1f-267cf3628685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
