<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Account Activity</name>
   <tag></tag>
   <elementGuidId>6f209748-ff00-41b8-8b8c-8a4add7fb5a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='account_activity_tab']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#account_activity_tab > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cdc34836-bbfc-45cf-b9bf-c80fc77cbaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/bank/redirect.html?url=account-activity.html</value>
      <webElementGuid>c19d233e-decc-4744-85a2-1cb072ef0e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account Activity</value>
      <webElementGuid>a4f06c2f-16b8-4447-81e7-e069b8d68f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account_activity_tab&quot;)/a[1]</value>
      <webElementGuid>087001dc-07b1-466f-91db-b48322f16589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='account_activity_tab']/a</value>
      <webElementGuid>6085dee7-e51c-4420-bcb6-ca86721c521a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Account Activity')]</value>
      <webElementGuid>55808ee2-4c47-4c75-bc4e-2edd3bf10c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Summary'])[1]/following::a[1]</value>
      <webElementGuid>e4d05176-3aa4-4d97-b6b8-767f5e3fe9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[2]</value>
      <webElementGuid>cf663371-be7c-4b4b-a873-ff84c77bc707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Funds'])[1]/preceding::a[1]</value>
      <webElementGuid>08cbceb5-b0ef-4147-a2a2-ed7db1e9d083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay Bills'])[1]/preceding::a[2]</value>
      <webElementGuid>ec14136c-1ecc-40dd-9aa0-b464e3edd47c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account Activity']/parent::*</value>
      <webElementGuid>3342bb43-777d-4343-a243-15ab1ce4cf76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/bank/redirect.html?url=account-activity.html')]</value>
      <webElementGuid>72492dc7-e504-4859-a213-8a4ae7af6d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>fb3a94f5-67b5-4d31-bcbd-8481460245e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/bank/redirect.html?url=account-activity.html' and (text() = 'Account Activity' or . = 'Account Activity')]</value>
      <webElementGuid>38c57bfc-51b6-4616-8581-01ae73321bf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
