<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sex</name>
   <tag></tag>
   <elementGuidId>fba448f4-a0fa-491a-8795-bc364970525f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-sex-uk-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-sex-uk-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eed01763-aada-448a-a385-54c3d325aaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>c942e094-fcf3-4691-95cc-bd3f8ac607a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sex-uk-container</value>
      <webElementGuid>b2bc2195-0e16-46e5-afe2-bc26c333dd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sex</value>
      <webElementGuid>b85f04bd-7574-4d92-810c-451632c81331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sex</value>
      <webElementGuid>4bd55eea-ac32-466b-aae4-1b8138d30131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-sex-uk-container&quot;)</value>
      <webElementGuid>bbbcb51d-afdc-49fc-8687-8ee017d60975</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-sex-uk-container']</value>
      <webElementGuid>482d5d2f-c1cc-49a7-bd94-e049cfe6d413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate Your BMI'])[1]/following::span[4]</value>
      <webElementGuid>3e669683-289b-458e-a8ad-3e1332419fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BMI'])[2]/following::span[4]</value>
      <webElementGuid>4146693c-87ee-4515-bace-7cd92d911236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an activity factor:'])[2]/preceding::span[3]</value>
      <webElementGuid>84e4bf93-b642-4fd2-b6af-0a41bd28a858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/preceding::span[9]</value>
      <webElementGuid>cb03bfc2-9eaa-4e8b-9122-c01d07762106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>93578d1a-8052-494b-9936-9a3cf3c406a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-sex-uk-container' and @title = 'Sex' and (text() = 'Sex' or . = 'Sex')]</value>
      <webElementGuid>65474a81-8821-4403-9220-2a4f188f0fd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
