<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select an activity factor</name>
   <tag></tag>
   <elementGuidId>88644b87-485d-4c41-a4fb-dc4d49b32620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-activity_level-0l-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-activity_level-0l-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e63811b-92e8-460e-b961-25b5b16c7b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>5e03def5-5c7a-4279-9ce8-3809fe82d940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-activity_level-0l-container</value>
      <webElementGuid>c0a2795c-41ec-405f-ac7a-4078f5a3efea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select an activity factor:</value>
      <webElementGuid>6c6e05eb-e35a-4e9d-9ac0-5e59e0f91409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an activity factor:</value>
      <webElementGuid>8e96d99f-ec96-4c6f-90f2-4f0f8b4d59c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-activity_level-0l-container&quot;)</value>
      <webElementGuid>30837fb7-57e5-4fe2-b237-2fe2b6dc0f8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-activity_level-0l-container']</value>
      <webElementGuid>2d6e5ead-a70a-4cc1-9239-7258990e11a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[2]/following::span[6]</value>
      <webElementGuid>acb9059e-0ba8-406d-bfeb-533c5f12fbf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate Your BMI'])[1]/following::span[10]</value>
      <webElementGuid>aa3363c7-3355-4107-85bf-da8af3b1316e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/preceding::span[3]</value>
      <webElementGuid>bd697bef-5582-4144-a927-20855a13ffad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Timetable'])[1]/preceding::span[9]</value>
      <webElementGuid>6cc47d62-6ebe-4ae1-9222-488b4b8904c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/span/span/span</value>
      <webElementGuid>b63ac8e0-7ea7-4cb3-a04b-c987d6453ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-activity_level-0l-container' and @title = 'Select an activity factor:' and (text() = 'Select an activity factor:' or . = 'Select an activity factor:')]</value>
      <webElementGuid>2ae52db0-3ed4-437c-8d80-d9bcb7dce069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
