<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Account Summary</name>
   <tag></tag>
   <elementGuidId>7bdb1c75-e3fd-4855-b852-7d204a570b62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='account_summary_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#account_summary_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>64774b61-4184-453b-98c1-65e15623be36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headers</value>
      <webElementGuid>c64aadf8-b5a2-4d48-8682-eb86d24c57a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account_summary_link</value>
      <webElementGuid>7a549300-c041-4a13-9535-8a87cb6c6146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account Summary</value>
      <webElementGuid>192ece3d-7be3-4c07-b0f5-00172e208119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account_summary_link&quot;)</value>
      <webElementGuid>d8a7831e-325b-4077-aeac-5a9812a99f39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='account_summary_link']</value>
      <webElementGuid>736777ac-a252-47a1-b933-3a07ef6333be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='online_banking_features']/div/div/h4/span</value>
      <webElementGuid>ab5772fa-ace9-4675-b92f-be95de1b81fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Bank is trusted by over 1,000,000 customers world wide.'])[1]/following::span[1]</value>
      <webElementGuid>20345681-cb79-47b2-9aea-bbd998070885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Banking'])[2]/following::span[1]</value>
      <webElementGuid>77bb891b-4c77-45ef-a6f7-cf48dbf61778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Activity'])[1]/preceding::span[1]</value>
      <webElementGuid>240fcf40-8677-4d9e-b93c-3ddcd5c0a683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Funds'])[1]/preceding::span[2]</value>
      <webElementGuid>fbda14f2-151a-4217-9bee-19de72d43733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account Summary']/parent::*</value>
      <webElementGuid>4caf55c9-acd8-49f6-b560-3fbe43e99176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>e32d5588-70e0-4b91-835a-6a3c6bc03236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'account_summary_link' and (text() = 'Account Summary' or . = 'Account Summary')]</value>
      <webElementGuid>5b7be3a6-75ca-4157-91e3-56f15632207c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
