<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2009</name>
   <tag></tag>
   <elementGuidId>467f532b-e669-4666-b393-cb0d4cc3353f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='online_statements_for_account']/div/div/div[2]/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9fcb8610-ef24-4304-9771-9c6ad897fcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#os_2009</value>
      <webElementGuid>6e929f5d-2fb8-4bb8-8818-b745c78ee0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>f1c137b7-bc0e-4de7-9caa-9112add521fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2009</value>
      <webElementGuid>d77cc3d9-afb8-46a9-9096-22554dd7243c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;online_statements_for_account&quot;)/div[@class=&quot;board&quot;]/div[@class=&quot;board-content&quot;]/div[@class=&quot;pull-left&quot;]/ul[@class=&quot;nav nav-pills&quot;]/li[4]/a[1]</value>
      <webElementGuid>81daea47-2799-4267-9c78-676565c4e36a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='online_statements_for_account']/div/div/div[2]/ul/li[4]/a</value>
      <webElementGuid>4cb083f6-224f-41e9-8cea-5665f5fe7560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2009')]</value>
      <webElementGuid>fa791dd6-590d-4830-948e-07c12e7a949b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Statements'])[1]/following::a[4]</value>
      <webElementGuid>f1223d45-d64e-484d-8bc7-1ab3eeca5779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account - Savings'])[1]/following::a[4]</value>
      <webElementGuid>fe2cba22-8929-4416-8b55-057787a4f5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statements (in PDF format)'])[1]/preceding::a[1]</value>
      <webElementGuid>153f65f8-5195-4a84-a822-65013ba72cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statement 01/10/12(57K)'])[1]/preceding::a[1]</value>
      <webElementGuid>27ae3328-0f50-49df-93ef-ea66989b9c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2009']/parent::*</value>
      <webElementGuid>131bfa34-71f9-4876-bb8f-1e87bb5c63e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#os_2009')]</value>
      <webElementGuid>04ea62a5-7e0c-4ca5-8210-dc23977ce857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]/a</value>
      <webElementGuid>9f3ee2e8-8f90-4bda-90e8-b8ba8070ecb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#os_2009' and (text() = '2009' or . = '2009')]</value>
      <webElementGuid>43bed6f7-edab-42b8-8c71-c7e1544c643d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
