<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Settings_caret</name>
   <tag></tag>
   <elementGuidId>5b595a4f-2797-4692-8bc4-d3eccdde624c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='settingsBox']/ul/li[2]/a/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b.caret</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>e2a628c7-0dd1-4b61-aa77-2ecd800b4ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
      <webElementGuid>8e9429f9-72e6-4018-8538-a9b3e4dfb16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settingsBox&quot;)/ul[@class=&quot;nav float-right&quot;]/li[@class=&quot;dropdown&quot;]/a[@class=&quot;dropdown-toggle&quot;]/b[@class=&quot;caret&quot;]</value>
      <webElementGuid>aa698377-851b-4f67-a3e6-ae12122fbe89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settingsBox']/ul/li[2]/a/b</value>
      <webElementGuid>dca02224-8cdd-4d2a-b783-a802cf86998b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>fbdc53db-8732-4aee-888e-0e5b10bdb7b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
