<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Savings                             _68be4f</name>
   <tag></tag>
   <elementGuidId>d13e6b48-c07c-4fb0-a5fe-9ef8c62cc322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='os_accountId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#os_accountId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4629da70-4a4d-4e26-bf68-7c2071679131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>os_accountId</value>
      <webElementGuid>ee293ae4-c606-40fc-a8aa-b749ce3bb66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountId</value>
      <webElementGuid>b63e16c0-fcff-47c0-8dd9-1a19df1602f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-xlarge</value>
      <webElementGuid>e78b2e8d-befe-4682-bade-b1346f57334b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>72e02df3-6371-45ec-835b-adc407862b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Savings
                                                Checking
                                                Savings
                                                Loan
                                                Credit Card
                                                Brokerage
                                        </value>
      <webElementGuid>dbc85703-d452-4362-89aa-84db1da0c6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;os_accountId&quot;)</value>
      <webElementGuid>be310172-3cce-47b2-9ea7-4734cd55cf51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='os_accountId']</value>
      <webElementGuid>123e2ba4-2411-496e-b2fa-189d86353e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::select[1]</value>
      <webElementGuid>874a423e-e4bb-47f4-825f-3a6ca5b04f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statements &amp; Documents'])[1]/following::select[1]</value>
      <webElementGuid>cc7fef52-47bf-4bff-8c56-e82289746cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account - Savings'])[1]/preceding::select[1]</value>
      <webElementGuid>3836d68c-3731-4d20-9ea5-f4020d977758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Statements'])[1]/preceding::select[1]</value>
      <webElementGuid>c9fbe570-473e-4c2c-a25b-2f0115a80c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6f1dbfb6-3f84-4dca-90d3-08a2f12ccb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'os_accountId' and @name = 'accountId' and (text() = '
                                                Savings
                                                Checking
                                                Savings
                                                Loan
                                                Credit Card
                                                Brokerage
                                        ' or . = '
                                                Savings
                                                Checking
                                                Savings
                                                Loan
                                                Credit Card
                                                Brokerage
                                        ')]</value>
      <webElementGuid>f8e32d0a-408e-4d2f-8b40-7234c4c426d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
